# syntax=docker/dockerfile:1
#artifactory.releng.ginkgo.zone/docker/
FROM artifactory.releng.ginkgo.zone/docker/python:3.8

# set a directory for the app
WORKDIR /usr/src/app

# copy all the files to the container
COPY . .

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# install ffmpeg
RUN apt-get -y update
RUN apt-get install -y ffmpeg

# define the port number the container should expose
# EXPOSE 5000

# run the command
ENTRYPOINT ["python", "./main.py"]